name: Build and Run Dockerfile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t workshop-python-selenium-gherkin .

    # Run the Docker container
    - name: Run Docker container
      run: |
        docker run --rm workshop-python-selenium-gherkin